// Generated by CoffeeScript 1.7.1
(function() {
  (function() {
    var log, testObject;
    log = function() {
      var e;
      try {
        console.log.apply(console, arguments);
      } catch (_error) {
        e = _error;
        try {
          opera.postError.apply(opera, arguments);
        } catch (_error) {
          e = _error;
          alert(Array.prototype.join.call(arguments, " "));
        }
      }
    };
    testObject = void 0;
    testObject = {
      name: "Awesome...",
      age: 23
    };
    log(testObject);
  })();

}).call(this);
